import { evaluateSoftware, SoftwareAssessmentInput } from '@/domain/decision-engine';

export interface VerifiedProductSeed {
  name: string;
  slug: string;
  categoryName: string;
  categorySlug: string;
  shortDescription: string;
  summary: string;
  websiteUrl: string;
  aliases: string[];
  assessment: SoftwareAssessmentInput;
  pricing: {
    name: string;
    billingInterval: string;
    basePrice: number;
    pricePerSeat: number;
    freeTier: boolean;
  }[];
  sources: {
    type: 'OFFICIAL_WEBSITE' | 'OFFICIAL_PRICING' | 'GITHUB' | 'REPUTABLE_SECONDARY';
    title: string;
    url: string;
  }[];
  openSourceAlternatives?: {
    name: string;
    githubUrl: string;
    description: string;
    stars: string;
  }[];
  verifiedCommercialAlternatives?: {
    name: string;
    slug: string;
    startingPrice: string;
    freeTier: boolean;
    featureParity: string;
    keyAdvantage: string;
  }[];
}

export const INITIAL_25_PRODUCTS: VerifiedProductSeed[] = [
  {
    name: 'Calendly',
    slug: 'calendly',
    categoryName: 'Scheduling & Meetings',
    categorySlug: 'scheduling',
    shortDescription: 'Hub for scheduling meetings professionally and efficiently without back-and-forth emails.',
    summary: 'Calendly streamlines appointment scheduling for teams and individuals by offering flexible availability controls and direct calendar integrations.',
    websiteUrl: 'https://calendly.com',
    aliases: ['Calendly Meeting', 'Calendly App'],
    assessment: {
      buildComplexity: 2,
      integrationDependency: 4,
      dataMoat: 2,
      networkEffects: 3,
      complianceRequirement: 2,
      infrastructureComplexity: 2,
      realtimeCollaboration: 2,
      maintenanceBurden: 2,
      businessCriticality: 3,
      migrationComplexity: 1,
      apiAvailability: 4,
      workflowAutomatable: 4,
      openSourceMaturity: 5,
      alternativeMarketStrength: 5,
      dataPortability: 4,
      mobileDependency: 2,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 2,
    },
    pricing: [
      { name: 'Free', billingInterval: 'monthly', basePrice: 0, pricePerSeat: 0, freeTier: true },
      { name: 'Standard', billingInterval: 'monthly', basePrice: 12, pricePerSeat: 10, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Calendly Official Home', url: 'https://calendly.com' },
      { type: 'OFFICIAL_PRICING', title: 'Calendly Official Pricing', url: 'https://calendly.com/pricing' },
    ],
    openSourceAlternatives: [
      { name: 'Cal.com', githubUrl: 'https://github.com/calcom/cal.com', description: 'Open-source scheduling infrastructure for everyone.', stars: '32.5k★' },
      { name: 'EasyAppointments', githubUrl: 'https://github.com/alextselegidis/easyappointments', description: 'Self-hosted appointment scheduler.', stars: '4.1k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Acuity Scheduling', slug: 'acuity', startingPrice: '$16/mo', freeTier: false, featureParity: '95%', keyAdvantage: 'Advanced client intake forms & payment processing.' },
      { name: 'Chili Piper', slug: 'chili-piper', startingPrice: '$15/mo', freeTier: false, featureParity: '90%', keyAdvantage: 'B2B inbound lead routing and instant sales qualified calls.' },
      { name: 'HubSpot Meetings', slug: 'hubspot-meetings', startingPrice: 'Free / $20', freeTier: true, featureParity: '88%', keyAdvantage: 'Native two-way HubSpot CRM contact sync.' },
    ],
  },
  {
    name: 'Typeform',
    slug: 'typeform',
    categoryName: 'Forms & Surveys',
    categorySlug: 'forms',
    shortDescription: 'Interactive online form builder designed for high-converting user engagement.',
    summary: 'Typeform provides conversational forms, quizzes, and surveys designed to maximize completion rates through minimalist design.',
    websiteUrl: 'https://typeform.com',
    aliases: ['Type Form', 'Typeform Survey'],
    assessment: {
      buildComplexity: 3,
      integrationDependency: 3,
      dataMoat: 2,
      networkEffects: 1,
      complianceRequirement: 3,
      infrastructureComplexity: 2,
      realtimeCollaboration: 2,
      maintenanceBurden: 2,
      businessCriticality: 3,
      migrationComplexity: 2,
      apiAvailability: 4,
      workflowAutomatable: 5,
      openSourceMaturity: 5,
      alternativeMarketStrength: 5,
      dataPortability: 4,
      mobileDependency: 2,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 2,
    },
    pricing: [
      { name: 'Basic', billingInterval: 'monthly', basePrice: 29, pricePerSeat: 0, freeTier: false },
      { name: 'Plus', billingInterval: 'monthly', basePrice: 59, pricePerSeat: 0, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Typeform Official Website', url: 'https://typeform.com' },
    ],
    openSourceAlternatives: [
      { name: 'Formbricks', githubUrl: 'https://github.com/formbricks/formbricks', description: 'Open-source survey software & experience management.', stars: '9.2k★' },
      { name: 'OhMyForm', githubUrl: 'https://github.com/ohmyform/ohmyform', description: 'Free & open-source form builder.', stars: '4.8k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Tally.so', slug: 'tally', startingPrice: 'Free / $29', freeTier: true, featureParity: '94%', keyAdvantage: '99% of features completely free with Notion-like editor.' },
      { name: 'Jotform', slug: 'jotform', startingPrice: '$34/mo', freeTier: true, featureParity: '98%', keyAdvantage: '10,000+ templates and advanced HIPAA compliance.' },
      { name: 'Fillout', slug: 'fillout', startingPrice: 'Free / $15', freeTier: true, featureParity: '92%', keyAdvantage: 'Native 2-way sync with Airtable, Notion, and Postgres.' },
    ],
  },
  {
    name: 'Zapier',
    slug: 'zapier',
    categoryName: 'Workflow Automation',
    categorySlug: 'automation',
    shortDescription: 'Automation platform connecting thousands of web applications without writing code.',
    summary: 'Zapier enables teams to build automated multi-step workflows between disparate SaaS tools.',
    websiteUrl: 'https://zapier.com',
    aliases: ['Zapier Automation', 'Zaps'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 5,
      dataMoat: 4,
      networkEffects: 4,
      complianceRequirement: 3,
      infrastructureComplexity: 4,
      realtimeCollaboration: 2,
      maintenanceBurden: 4,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 5,
      workflowAutomatable: 4,
      openSourceMaturity: 5,
      alternativeMarketStrength: 4,
      dataPortability: 3,
      mobileDependency: 1,
      permissionComplexity: 3,
      reliabilityRequirement: 5,
      vendorLockIn: 3,
    },
    pricing: [
      { name: 'Free', billingInterval: 'monthly', basePrice: 0, pricePerSeat: 0, freeTier: true },
      { name: 'Starter', billingInterval: 'monthly', basePrice: 29.99, pricePerSeat: 0, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Zapier Official Site', url: 'https://zapier.com' },
    ],
    openSourceAlternatives: [
      { name: 'n8n', githubUrl: 'https://github.com/n8n-io/n8n', description: 'Free and source-available workflow automation tool.', stars: '54.1k★' },
      { name: 'Activepieces', githubUrl: 'https://github.com/activepieces/activepieces', description: 'Open-source no-code business automation.', stars: '11.4k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Make.com', slug: 'make', startingPrice: '$10.59/mo', freeTier: true, featureParity: '96%', keyAdvantage: '70% lower task execution cost with visual canvas.' },
      { name: 'Pipedream', slug: 'pipedream', startingPrice: 'Free / $19', freeTier: true, featureParity: '90%', keyAdvantage: 'Developer-first integration platform with custom Node/Python code.' },
      { name: 'Workato', slug: 'workato', startingPrice: 'Enterprise', freeTier: false, featureParity: '99%', keyAdvantage: 'Enterprise governance, SOC2 Type II, and data transformation.' },
    ],
  },
  {
    name: 'Make',
    slug: 'make',
    categoryName: 'Workflow Automation',
    categorySlug: 'automation',
    shortDescription: 'Visual automation platform for designing complex custom integration workflows.',
    summary: 'Make (formerly Integromat) allows users to build, inspect, and automate visual workflows across web services.',
    websiteUrl: 'https://make.com',
    aliases: ['Integromat', 'Make.com'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 5,
      dataMoat: 4,
      networkEffects: 3,
      complianceRequirement: 3,
      infrastructureComplexity: 4,
      realtimeCollaboration: 2,
      maintenanceBurden: 4,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 5,
      workflowAutomatable: 5,
      openSourceMaturity: 5,
      alternativeMarketStrength: 4,
      dataPortability: 3,
      mobileDependency: 1,
      permissionComplexity: 3,
      reliabilityRequirement: 5,
      vendorLockIn: 3,
    },
    pricing: [
      { name: 'Core', billingInterval: 'monthly', basePrice: 10.59, pricePerSeat: 0, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Make Official Site', url: 'https://make.com' },
    ],
  },
  {
    name: 'Notion',
    slug: 'notion',
    categoryName: 'Workspace & Knowledge',
    categorySlug: 'knowledge',
    shortDescription: 'All-in-one workspace for notes, docs, wiki, databases, and project management.',
    summary: 'Notion provides block-based collaborative document editing paired with flexible relational databases.',
    websiteUrl: 'https://notion.so',
    aliases: ['Notion App', 'Notion HQ'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 3,
      dataMoat: 4,
      networkEffects: 3,
      complianceRequirement: 3,
      infrastructureComplexity: 3,
      realtimeCollaboration: 5,
      maintenanceBurden: 3,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 4,
      workflowAutomatable: 3,
      openSourceMaturity: 4,
      alternativeMarketStrength: 4,
      dataPortability: 3,
      mobileDependency: 3,
      permissionComplexity: 3,
      reliabilityRequirement: 4,
      vendorLockIn: 4,
    },
    pricing: [
      { name: 'Free', billingInterval: 'monthly', basePrice: 0, pricePerSeat: 0, freeTier: true },
      { name: 'Plus', billingInterval: 'monthly', basePrice: 10, pricePerSeat: 8, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Notion Official Website', url: 'https://notion.so' },
    ],
    openSourceAlternatives: [
      { name: 'AppFlowy', githubUrl: 'https://github.com/AppFlowy-IO/AppFlowy', description: 'Open-source Notion alternative for data security.', stars: '52.4k★' },
      { name: 'AFFiNE', githubUrl: 'https://github.com/toeverything/AFFiNE', description: 'Hyper-fusion workspace combining docs and whiteboards.', stars: '38.1k★' },
    ],
  },
  {
    name: 'ClickUp',
    slug: 'clickup',
    categoryName: 'Project Management',
    categorySlug: 'project-management',
    shortDescription: 'All-in-one productivity platform replacing tasks, docs, goals, and chat.',
    summary: 'ClickUp bundles work management features into a unified tool with customizable views.',
    websiteUrl: 'https://clickup.com',
    aliases: ['Click Up', 'Clickup.com'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 4,
      dataMoat: 3,
      networkEffects: 2,
      complianceRequirement: 3,
      infrastructureComplexity: 3,
      realtimeCollaboration: 4,
      maintenanceBurden: 4,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 4,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 5,
      dataPortability: 4,
      mobileDependency: 3,
      permissionComplexity: 4,
      reliabilityRequirement: 4,
      vendorLockIn: 3,
    },
    pricing: [
      { name: 'Unlimited', billingInterval: 'monthly', basePrice: 10, pricePerSeat: 7, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'ClickUp Official Website', url: 'https://clickup.com' },
    ],
    openSourceAlternatives: [
      { name: 'Plane', githubUrl: 'https://github.com/makeplane/plane', description: 'Open-source project management software for software teams.', stars: '28.9k★' },
      { name: 'Taiga', githubUrl: 'https://github.com/taigaio/taiga-back', description: 'Agile project management platform.', stars: '7.2k★' },
    ],
  },
  {
    name: 'Airtable',
    slug: 'airtable',
    categoryName: 'Low-Code & Databases',
    categorySlug: 'databases',
    shortDescription: 'Low-code platform for building collaborative database applications.',
    summary: 'Airtable combines relational database power with spreadsheet familiarity to build custom workflow apps.',
    websiteUrl: 'https://airtable.com',
    aliases: ['Air Table', 'Airtable DB'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 4,
      dataMoat: 4,
      networkEffects: 2,
      complianceRequirement: 3,
      infrastructureComplexity: 4,
      realtimeCollaboration: 5,
      maintenanceBurden: 3,
      businessCriticality: 4,
      migrationComplexity: 4,
      apiAvailability: 5,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 4,
      dataPortability: 4,
      mobileDependency: 2,
      permissionComplexity: 4,
      reliabilityRequirement: 4,
      vendorLockIn: 4,
    },
    pricing: [
      { name: 'Team', billingInterval: 'monthly', basePrice: 24, pricePerSeat: 20, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Airtable Official Website', url: 'https://airtable.com' },
    ],
    openSourceAlternatives: [
      { name: 'NocoDB', githubUrl: 'https://github.com/nocodb/nocodb', description: 'Open-source Airtable alternative turning databases into smart spreadsheets.', stars: '45.8k★' },
      { name: 'Baserow', githubUrl: 'https://github.com/briefer/baserow', description: 'Open-source no-code database platform.', stars: '16.2k★' },
    ],
  },
  {
    name: 'Loom',
    slug: 'loom',
    categoryName: 'Video Communication',
    categorySlug: 'video',
    shortDescription: 'Asynchronous video messaging for fast team collaboration.',
    summary: 'Loom records quick video and screen messages to replace unnecessary meetings.',
    websiteUrl: 'https://loom.com',
    aliases: ['Loom Video', 'Loom Message'],
    assessment: {
      buildComplexity: 3,
      integrationDependency: 2,
      dataMoat: 2,
      networkEffects: 2,
      complianceRequirement: 2,
      infrastructureComplexity: 4,
      realtimeCollaboration: 2,
      maintenanceBurden: 3,
      businessCriticality: 2,
      migrationComplexity: 1,
      apiAvailability: 3,
      workflowAutomatable: 3,
      openSourceMaturity: 3,
      alternativeMarketStrength: 4,
      dataPortability: 3,
      mobileDependency: 2,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 1,
    },
    pricing: [
      { name: 'Business', billingInterval: 'monthly', basePrice: 12.50, pricePerSeat: 10, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Loom Official Website', url: 'https://loom.com' },
    ],
    openSourceAlternatives: [
      { name: 'Cap', githubUrl: 'https://github.com/CapSoftware/Cap', description: 'Open-source Loom alternative for effortless video sharing.', stars: '6.5k★' },
    ],
  },
  {
    name: 'HubSpot',
    slug: 'hubspot',
    categoryName: 'CRM & Marketing',
    categorySlug: 'crm',
    shortDescription: 'Inbound marketing, sales CRM, and customer service suite.',
    summary: 'HubSpot delivers an enterprise CRM platform combining sales pipelines, marketing automation, and support.',
    websiteUrl: 'https://hubspot.com',
    aliases: ['Hubspot CRM', 'HubSpot Sales'],
    assessment: {
      buildComplexity: 5,
      integrationDependency: 5,
      dataMoat: 5,
      networkEffects: 3,
      complianceRequirement: 4,
      infrastructureComplexity: 5,
      realtimeCollaboration: 3,
      maintenanceBurden: 5,
      businessCriticality: 5,
      migrationComplexity: 5,
      apiAvailability: 5,
      workflowAutomatable: 3,
      openSourceMaturity: 3,
      alternativeMarketStrength: 4,
      dataPortability: 3,
      mobileDependency: 3,
      permissionComplexity: 5,
      reliabilityRequirement: 5,
      vendorLockIn: 5,
    },
    pricing: [
      { name: 'Starter', billingInterval: 'monthly', basePrice: 50, pricePerSeat: 20, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'HubSpot Official Website', url: 'https://hubspot.com' },
    ],
    openSourceAlternatives: [
      { name: 'Twenty', githubUrl: 'https://github.com/twentyhq/twenty', description: 'Modern open-source CRM platform.', stars: '21.4k★' },
      { name: 'SuiteCRM', githubUrl: 'https://github.com/salesagility/SuiteCRM', description: 'Open-source enterprise CRM software.', stars: '4.3k★' },
    ],
  },
  {
    name: 'Mailchimp',
    slug: 'mailchimp',
    categoryName: 'Email Marketing',
    categorySlug: 'email-marketing',
    shortDescription: 'Marketing automation and email marketing service for businesses.',
    summary: 'Mailchimp provides tools for building email campaigns, landing pages, and automated customer journeys.',
    websiteUrl: 'https://mailchimp.com',
    aliases: ['Mail Chimp', 'Intuit Mailchimp'],
    assessment: {
      buildComplexity: 3,
      integrationDependency: 4,
      dataMoat: 3,
      networkEffects: 1,
      complianceRequirement: 4,
      infrastructureComplexity: 3,
      realtimeCollaboration: 2,
      maintenanceBurden: 3,
      businessCriticality: 4,
      migrationComplexity: 2,
      apiAvailability: 4,
      workflowAutomatable: 4,
      openSourceMaturity: 5,
      alternativeMarketStrength: 5,
      dataPortability: 4,
      mobileDependency: 2,
      permissionComplexity: 2,
      reliabilityRequirement: 5,
      vendorLockIn: 2,
    },
    pricing: [
      { name: 'Essentials', billingInterval: 'monthly', basePrice: 13, pricePerSeat: 0, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Mailchimp Official Website', url: 'https://mailchimp.com' },
    ],
    openSourceAlternatives: [
      { name: 'Listmonk', githubUrl: 'https://github.com/knadh/listmonk', description: 'High-performance self-hosted newsletter manager.', stars: '14.8k★' },
      { name: 'Mautic', githubUrl: 'https://github.com/mautic/mautic', description: 'Open-source marketing automation software.', stars: '7.1k★' },
    ],
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    categoryName: 'AI Code Editor',
    categorySlug: 'ai-code-editor',
    shortDescription: 'AI-first code editor designed for pair programming and repository indexing.',
    summary: 'Cursor is an intelligent fork of VS Code built from the ground up for deep AI codebase assistance.',
    websiteUrl: 'https://cursor.com',
    aliases: ['Cursor IDE', 'Cursor AI'],
    assessment: {
      buildComplexity: 5,
      integrationDependency: 2,
      dataMoat: 3,
      networkEffects: 2,
      complianceRequirement: 3,
      infrastructureComplexity: 4,
      realtimeCollaboration: 2,
      maintenanceBurden: 4,
      businessCriticality: 4,
      migrationComplexity: 1,
      apiAvailability: 3,
      workflowAutomatable: 2,
      openSourceMaturity: 3,
      alternativeMarketStrength: 4,
      dataPortability: 5,
      mobileDependency: 1,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 1,
    },
    pricing: [
      { name: 'Pro', billingInterval: 'monthly', basePrice: 20, pricePerSeat: 20, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Cursor Official Website', url: 'https://cursor.com' },
    ],
  },
  {
    name: 'Lovable',
    slug: 'lovable',
    categoryName: 'AI Web Builder',
    categorySlug: 'ai-web-builder',
    shortDescription: 'AI engineer turning prompt ideas into full-stack web applications.',
    summary: 'Lovable builds scalable full-stack web apps using plain language prompts and automatic code generation.',
    websiteUrl: 'https://lovable.dev',
    aliases: ['Lovable AI', 'Lovable Dev'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 3,
      dataMoat: 2,
      networkEffects: 1,
      complianceRequirement: 2,
      infrastructureComplexity: 3,
      realtimeCollaboration: 2,
      maintenanceBurden: 3,
      businessCriticality: 3,
      migrationComplexity: 2,
      apiAvailability: 3,
      workflowAutomatable: 3,
      openSourceMaturity: 2,
      alternativeMarketStrength: 3,
      dataPortability: 4,
      mobileDependency: 1,
      permissionComplexity: 2,
      reliabilityRequirement: 3,
      vendorLockIn: 2,
    },
    pricing: [
      { name: 'Pro', billingInterval: 'monthly', basePrice: 20, pricePerSeat: 20, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Lovable Official Website', url: 'https://lovable.dev' },
    ],
  },
  {
    name: 'Canva',
    slug: 'canva',
    categoryName: 'Design & Graphics',
    categorySlug: 'design',
    shortDescription: 'Online visual design suite for creating social media graphics, presentations, and documents.',
    summary: 'Canva democratizes graphic design with thousands of templates and drag-and-drop visual tools.',
    websiteUrl: 'https://canva.com',
    aliases: ['Canva Design'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 2,
      dataMoat: 3,
      networkEffects: 3,
      complianceRequirement: 2,
      infrastructureComplexity: 4,
      realtimeCollaboration: 4,
      maintenanceBurden: 4,
      businessCriticality: 3,
      migrationComplexity: 2,
      apiAvailability: 3,
      workflowAutomatable: 2,
      openSourceMaturity: 3,
      alternativeMarketStrength: 4,
      dataPortability: 3,
      mobileDependency: 3,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 3,
    },
    pricing: [
      { name: 'Pro', billingInterval: 'monthly', basePrice: 15, pricePerSeat: 13, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Canva Official Website', url: 'https://canva.com' },
    ],
  },
  {
    name: 'Intercom',
    slug: 'intercom',
    categoryName: 'Customer Support & Chat',
    categorySlug: 'customer-support',
    shortDescription: 'AI-first customer service platform for live chat and support automation.',
    summary: 'Intercom offers live chat, help centers, and AI support bots for automated customer assistance.',
    websiteUrl: 'https://intercom.com',
    aliases: ['Intercom Chat', 'Intercom AI'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 4,
      dataMoat: 4,
      networkEffects: 2,
      complianceRequirement: 3,
      infrastructureComplexity: 4,
      realtimeCollaboration: 4,
      maintenanceBurden: 4,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 4,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 5,
      dataPortability: 3,
      mobileDependency: 2,
      permissionComplexity: 3,
      reliabilityRequirement: 5,
      vendorLockIn: 4,
    },
    pricing: [
      { name: 'Essential', billingInterval: 'monthly', basePrice: 39, pricePerSeat: 39, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Intercom Official Website', url: 'https://intercom.com' },
    ],
  },
  {
    name: 'Shopify',
    slug: 'shopify',
    categoryName: 'E-Commerce Platform',
    categorySlug: 'ecommerce',
    shortDescription: 'All-in-one commerce platform for online stores and retail point-of-sale.',
    summary: 'Shopify powers global online storefronts with payments, order management, and app integrations.',
    websiteUrl: 'https://shopify.com',
    aliases: ['Shopify Store', 'Shopify Plus'],
    assessment: {
      buildComplexity: 5,
      integrationDependency: 5,
      dataMoat: 5,
      networkEffects: 4,
      complianceRequirement: 5,
      infrastructureComplexity: 5,
      realtimeCollaboration: 2,
      maintenanceBurden: 5,
      businessCriticality: 5,
      migrationComplexity: 4,
      apiAvailability: 5,
      workflowAutomatable: 3,
      openSourceMaturity: 4,
      alternativeMarketStrength: 4,
      dataPortability: 4,
      mobileDependency: 3,
      permissionComplexity: 4,
      reliabilityRequirement: 5,
      vendorLockIn: 4,
    },
    pricing: [
      { name: 'Basic', billingInterval: 'monthly', basePrice: 39, pricePerSeat: 0, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Shopify Official Website', url: 'https://shopify.com' },
    ],
  },
  {
    name: 'Webflow',
    slug: 'webflow',
    categoryName: 'Website Builder & CMS',
    categorySlug: 'website-builder',
    shortDescription: 'Visual web design tool and CMS platform producing production HTML/CSS.',
    summary: 'Webflow lets designers build custom, responsive websites without code while retaining complete CSS layout control.',
    websiteUrl: 'https://webflow.com',
    aliases: ['Web Flow'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 3,
      dataMoat: 3,
      networkEffects: 2,
      complianceRequirement: 2,
      infrastructureComplexity: 3,
      realtimeCollaboration: 3,
      maintenanceBurden: 3,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 4,
      workflowAutomatable: 3,
      openSourceMaturity: 4,
      alternativeMarketStrength: 4,
      dataPortability: 4,
      mobileDependency: 1,
      permissionComplexity: 3,
      reliabilityRequirement: 4,
      vendorLockIn: 3,
    },
    pricing: [
      { name: 'Core', billingInterval: 'monthly', basePrice: 29, pricePerSeat: 0, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Webflow Official Website', url: 'https://webflow.com' },
    ],
  },
  {
    name: 'Miro',
    slug: 'miro',
    categoryName: 'Digital Whiteboard',
    categorySlug: 'whiteboard',
    shortDescription: 'Visual workspace and online whiteboarding platform for distributed teams.',
    summary: 'Miro provides an infinite canvas for brainstorming, diagramming, agile mapping, and project planning.',
    websiteUrl: 'https://miro.com',
    aliases: ['RealtimeBoard', 'Miro Canvas'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 3,
      dataMoat: 3,
      networkEffects: 3,
      complianceRequirement: 3,
      infrastructureComplexity: 4,
      realtimeCollaboration: 5,
      maintenanceBurden: 3,
      businessCriticality: 3,
      migrationComplexity: 2,
      apiAvailability: 3,
      workflowAutomatable: 2,
      openSourceMaturity: 3,
      alternativeMarketStrength: 4,
      dataPortability: 3,
      mobileDependency: 2,
      permissionComplexity: 3,
      reliabilityRequirement: 4,
      vendorLockIn: 3,
    },
    pricing: [
      { name: 'Starter', billingInterval: 'monthly', basePrice: 10, pricePerSeat: 8, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Miro Official Website', url: 'https://miro.com' },
    ],
  },
  {
    name: 'Zendesk',
    slug: 'zendesk',
    categoryName: 'Customer Support & Chat',
    categorySlug: 'customer-support',
    shortDescription: 'Customer service software and sales CRM solution.',
    summary: 'Zendesk builds enterprise ticketing, help center software, and omnichannel customer communication channels.',
    websiteUrl: 'https://zendesk.com',
    aliases: ['Zendesk Support', 'Zendesk Suite'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 4,
      dataMoat: 4,
      networkEffects: 2,
      complianceRequirement: 4,
      infrastructureComplexity: 4,
      realtimeCollaboration: 3,
      maintenanceBurden: 4,
      businessCriticality: 4,
      migrationComplexity: 4,
      apiAvailability: 5,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 5,
      dataPortability: 3,
      mobileDependency: 2,
      permissionComplexity: 4,
      reliabilityRequirement: 5,
      vendorLockIn: 4,
    },
    pricing: [
      { name: 'Suite Team', billingInterval: 'monthly', basePrice: 55, pricePerSeat: 55, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Zendesk Official Website', url: 'https://zendesk.com' },
    ],
  },
  {
    name: 'Asana',
    slug: 'asana',
    categoryName: 'Project Management',
    categorySlug: 'project-management',
    shortDescription: 'Work management platform designed to organize tasks and project workflows.',
    summary: 'Asana offers structured task tracking, timelines, and goal management for team alignment.',
    websiteUrl: 'https://asana.com',
    aliases: ['Asana Project'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 4,
      dataMoat: 3,
      networkEffects: 2,
      complianceRequirement: 3,
      infrastructureComplexity: 3,
      realtimeCollaboration: 4,
      maintenanceBurden: 3,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 4,
      workflowAutomatable: 3,
      openSourceMaturity: 4,
      alternativeMarketStrength: 5,
      dataPortability: 4,
      mobileDependency: 3,
      permissionComplexity: 4,
      reliabilityRequirement: 4,
      vendorLockIn: 3,
    },
    pricing: [
      { name: 'Starter', billingInterval: 'monthly', basePrice: 13.49, pricePerSeat: 10.99, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Asana Official Website', url: 'https://asana.com' },
    ],
  },
  {
    name: 'Monday',
    slug: 'monday',
    categoryName: 'Project Management',
    categorySlug: 'project-management',
    shortDescription: 'Work OS platform to manage projects, processes, and daily tasks.',
    summary: 'Monday.com provides visually intuitive workboards and custom status automation for operational teams.',
    websiteUrl: 'https://monday.com',
    aliases: ['Monday.com', 'Monday Work OS'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 4,
      dataMoat: 3,
      networkEffects: 2,
      complianceRequirement: 3,
      infrastructureComplexity: 3,
      realtimeCollaboration: 4,
      maintenanceBurden: 3,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 4,
      workflowAutomatable: 3,
      openSourceMaturity: 4,
      alternativeMarketStrength: 5,
      dataPortability: 4,
      mobileDependency: 3,
      permissionComplexity: 3,
      reliabilityRequirement: 4,
      vendorLockIn: 3,
    },
    pricing: [
      { name: 'Standard', billingInterval: 'monthly', basePrice: 14, pricePerSeat: 12, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Monday.com Official Website', url: 'https://monday.com' },
    ],
    openSourceAlternatives: [
      { name: 'Plane', githubUrl: 'https://github.com/makeplane/plane', description: 'Open-source project management workspace.', stars: '28.9k★' },
      { name: 'OpenProject', githubUrl: 'https://github.com/opf/openproject', description: 'Open-source classic project management software.', stars: '8.4k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'ClickUp', slug: 'clickup', startingPrice: '$10/mo', freeTier: true, featureParity: '96%', keyAdvantage: 'More granular custom task views & lower per-seat price.' },
      { name: 'Asana', slug: 'asana', startingPrice: '$13.49/mo', freeTier: true, featureParity: '94%', keyAdvantage: 'Superior cross-project portfolio management.' },
    ],
  },
  {
    name: 'Linktree',
    slug: 'linktree',
    categoryName: 'Bio Link & Landing',
    categorySlug: 'bio-link',
    shortDescription: 'Bio link platform for creators to share links and content in one place.',
    summary: 'Linktree centralizes social profiles, content, and links into a single mobile-optimized landing page.',
    websiteUrl: 'https://linktr.ee',
    aliases: ['Link Tree', 'Linktr.ee'],
    assessment: {
      buildComplexity: 1,
      integrationDependency: 2,
      dataMoat: 1,
      networkEffects: 1,
      complianceRequirement: 1,
      infrastructureComplexity: 1,
      realtimeCollaboration: 1,
      maintenanceBurden: 1,
      businessCriticality: 2,
      migrationComplexity: 1,
      apiAvailability: 3,
      workflowAutomatable: 4,
      openSourceMaturity: 5,
      alternativeMarketStrength: 5,
      dataPortability: 5,
      mobileDependency: 3,
      permissionComplexity: 1,
      reliabilityRequirement: 3,
      vendorLockIn: 1,
    },
    pricing: [
      { name: 'Pro', billingInterval: 'monthly', basePrice: 9, pricePerSeat: 0, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Linktree Official Website', url: 'https://linktr.ee' },
    ],
    openSourceAlternatives: [
      { name: 'LittleLink', githubUrl: 'https://github.com/sethcottle/littlelink', description: 'Lightweight open-source Linktree alternative.', stars: '4.9k★' },
      { name: 'LinkFree (BioDrop)', githubUrl: 'https://github.com/EddieHubCommunity/BioDrop', description: 'Connect your audience with a single link.', stars: '4.2k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Bento.me', slug: 'bento', startingPrice: 'Free', freeTier: true, featureParity: '98%', keyAdvantage: 'Stunning modern visual grid layout.' },
      { name: 'Beacons', slug: 'beacons', startingPrice: 'Free / $10', freeTier: true, featureParity: '95%', keyAdvantage: 'Integrated creator store & email marketing.' },
    ],
  },
  {
    name: 'ConvertKit',
    slug: 'convertkit',
    categoryName: 'Email Marketing',
    categorySlug: 'email-marketing',
    shortDescription: 'Email marketing and creator platform for digital newsletter publishers.',
    summary: 'ConvertKit (now Kit) offers audience growth tools, automation sequences, and digital product checkout for creators.',
    websiteUrl: 'https://convertkit.com',
    aliases: ['Kit', 'Convert Kit'],
    assessment: {
      buildComplexity: 3,
      integrationDependency: 3,
      dataMoat: 3,
      networkEffects: 2,
      complianceRequirement: 3,
      infrastructureComplexity: 3,
      realtimeCollaboration: 2,
      maintenanceBurden: 3,
      businessCriticality: 4,
      migrationComplexity: 2,
      apiAvailability: 4,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 4,
      dataPortability: 4,
      mobileDependency: 2,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 2,
    },
    pricing: [
      { name: 'Creator', billingInterval: 'monthly', basePrice: 29, pricePerSeat: 0, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'ConvertKit Official Website', url: 'https://convertkit.com' },
    ],
    openSourceAlternatives: [
      { name: 'Listmonk', githubUrl: 'https://github.com/knadh/listmonk', description: 'High-performance newsletter & mailing list manager.', stars: '14.8k★' },
      { name: 'Ghost', githubUrl: 'https://github.com/TryGhost/Ghost', description: 'Open-source publishing & newsletter platform.', stars: '47.1k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'beehiiv', slug: 'beehiiv', startingPrice: 'Free / $42', freeTier: true, featureParity: '96%', keyAdvantage: 'Built-in newsletter ad network & referral program.' },
      { name: 'Substack', slug: 'substack', startingPrice: 'Free (10% fee)', freeTier: true, featureParity: '90%', keyAdvantage: 'Zero monthly cost for free newsletters.' },
    ],
  },
  {
    name: 'Buffer',
    slug: 'buffer',
    categoryName: 'Social Media Management',
    categorySlug: 'social-media',
    shortDescription: 'Social media scheduling and publishing platform for multi-channel posts.',
    summary: 'Buffer schedules posts, analyzes social performance, and manages social media channel queues.',
    websiteUrl: 'https://buffer.com',
    aliases: ['Buffer App', 'Buffer Publish'],
    assessment: {
      buildComplexity: 2,
      integrationDependency: 4,
      dataMoat: 2,
      networkEffects: 1,
      complianceRequirement: 2,
      infrastructureComplexity: 2,
      realtimeCollaboration: 2,
      maintenanceBurden: 2,
      businessCriticality: 3,
      migrationComplexity: 1,
      apiAvailability: 3,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 4,
      dataPortability: 4,
      mobileDependency: 3,
      permissionComplexity: 2,
      reliabilityRequirement: 3,
      vendorLockIn: 1,
    },
    pricing: [
      { name: 'Essentials', billingInterval: 'monthly', basePrice: 6, pricePerSeat: 6, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Buffer Official Website', url: 'https://buffer.com' },
    ],
    openSourceAlternatives: [
      { name: 'Postiz', githubUrl: 'https://github.com/gitroomhq/postiz-app', description: 'Open-source AI-assisted social media scheduling tool.', stars: '14.2k★' },
      { name: 'Mixpost', githubUrl: 'https://github.com/inovector/mixpost', description: 'Self-hosted social media management software.', stars: '3.6k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Typefully', slug: 'typefully', startingPrice: '$12.50/mo', freeTier: true, featureParity: '94%', keyAdvantage: 'Dedicated X/Twitter & LinkedIn thread writing interface.' },
      { name: 'FeedHive', slug: 'feedhive', startingPrice: '$19/mo', freeTier: false, featureParity: '92%', keyAdvantage: 'AI conditional post recycling & visual grid calendar.' },
    ],
  },
  {
    name: 'Hootsuite',
    slug: 'hootsuite',
    categoryName: 'Social Media Management',
    categorySlug: 'social-media',
    shortDescription: 'Enterprise social media management and social listening platform.',
    summary: 'Hootsuite connects brand social channels for multi-user publishing, approval flows, and social analytics.',
    websiteUrl: 'https://hootsuite.com',
    aliases: ['Hoot Suite'],
    assessment: {
      buildComplexity: 3,
      integrationDependency: 4,
      dataMoat: 3,
      networkEffects: 1,
      complianceRequirement: 3,
      infrastructureComplexity: 3,
      realtimeCollaboration: 3,
      maintenanceBurden: 3,
      businessCriticality: 3,
      migrationComplexity: 2,
      apiAvailability: 3,
      workflowAutomatable: 3,
      openSourceMaturity: 4,
      alternativeMarketStrength: 4,
      dataPortability: 3,
      mobileDependency: 2,
      permissionComplexity: 3,
      reliabilityRequirement: 4,
      vendorLockIn: 2,
    },
    pricing: [
      { name: 'Professional', billingInterval: 'monthly', basePrice: 99, pricePerSeat: 99, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Hootsuite Official Website', url: 'https://hootsuite.com' },
    ],
  },
  {
    name: 'ActiveCampaign',
    slug: 'activecampaign',
    categoryName: 'CRM & Marketing',
    categorySlug: 'crm',
    shortDescription: 'Marketing automation, email marketing, and sales CRM platform.',
    summary: 'ActiveCampaign automates visual customer lifecycle journeys with email triggers and CRM pipelines.',
    websiteUrl: 'https://activecampaign.com',
    aliases: ['Active Campaign'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 4,
      dataMoat: 4,
      networkEffects: 2,
      complianceRequirement: 3,
      infrastructureComplexity: 4,
      realtimeCollaboration: 2,
      maintenanceBurden: 4,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 4,
      workflowAutomatable: 4,
      openSourceMaturity: 3,
      alternativeMarketStrength: 4,
      dataPortability: 3,
      mobileDependency: 2,
      permissionComplexity: 3,
      reliabilityRequirement: 4,
      vendorLockIn: 3,
    },
    pricing: [
      { name: 'Plus', billingInterval: 'monthly', basePrice: 49, pricePerSeat: 49, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'ActiveCampaign Official Website', url: 'https://activecampaign.com' },
    ],
  },
  {
    name: 'PostHog',
    slug: 'posthog',
    categoryName: 'Product Analytics',
    categorySlug: 'analytics',
    shortDescription: 'Open-source product analytics suite with session replay, feature flags, and A/B testing.',
    summary: 'PostHog provides product telemetry, funnel tracking, heatmaps, and feature rollout flags.',
    websiteUrl: 'https://posthog.com',
    aliases: ['Post Hog', 'PostHog Cloud'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 4,
      dataMoat: 4,
      networkEffects: 1,
      complianceRequirement: 4,
      infrastructureComplexity: 4,
      realtimeCollaboration: 2,
      maintenanceBurden: 4,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 5,
      workflowAutomatable: 3,
      openSourceMaturity: 5,
      alternativeMarketStrength: 4,
      dataPortability: 5,
      mobileDependency: 2,
      permissionComplexity: 3,
      reliabilityRequirement: 5,
      vendorLockIn: 2,
    },
    pricing: [
      { name: 'Free', billingInterval: 'monthly', basePrice: 0, pricePerSeat: 0, freeTier: true },
      { name: 'Scale', billingInterval: 'monthly', basePrice: 45, pricePerSeat: 0, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'PostHog Official Site', url: 'https://posthog.com' },
    ],
    openSourceAlternatives: [
      { name: 'PostHog Self-Hosted', githubUrl: 'https://github.com/PostHog/posthog', description: 'Open-source product analytics backend.', stars: '23.1k★' },
      { name: 'Mixpanel', githubUrl: 'https://github.com/mixpanel', description: 'Commercial product analytics platform.', stars: '1.2k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Mixpanel', slug: 'mixpanel', startingPrice: 'Free / $20', freeTier: true, featureParity: '94%', keyAdvantage: 'Faster event exploration & visual metric builder.' },
      { name: 'Amplitude', slug: 'amplitude', startingPrice: 'Free / $49', freeTier: true, featureParity: '96%', keyAdvantage: 'Advanced cohort retention & user pathing analysis.' },
    ],
  },
  {
    name: 'Supabase',
    slug: 'supabase',
    categoryName: 'Low-Code & Databases',
    categorySlug: 'databases',
    shortDescription: 'Open-source Firebase alternative providing Postgres, Auth, Storage, and Realtime Edge functions.',
    summary: 'Supabase combines managed Postgres database hosting with auto-generated REST/GraphQL APIs and authentication.',
    websiteUrl: 'https://supabase.com',
    aliases: ['Supabase DB', 'Supabase Cloud'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 5,
      dataMoat: 5,
      networkEffects: 2,
      complianceRequirement: 4,
      infrastructureComplexity: 4,
      realtimeCollaboration: 3,
      maintenanceBurden: 3,
      businessCriticality: 5,
      migrationComplexity: 4,
      apiAvailability: 5,
      workflowAutomatable: 4,
      openSourceMaturity: 5,
      alternativeMarketStrength: 4,
      dataPortability: 5,
      mobileDependency: 2,
      permissionComplexity: 4,
      reliabilityRequirement: 5,
      vendorLockIn: 2,
    },
    pricing: [
      { name: 'Free', billingInterval: 'monthly', basePrice: 0, pricePerSeat: 0, freeTier: true },
      { name: 'Pro', billingInterval: 'monthly', basePrice: 25, pricePerSeat: 0, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Supabase Official Site', url: 'https://supabase.com' },
    ],
    openSourceAlternatives: [
      { name: 'Supabase Self-Hosted', githubUrl: 'https://github.com/supabase/supabase', description: 'Open-source Firebase alternative built on PostgreSQL.', stars: '74.5k★' },
      { name: 'PocketBase', githubUrl: 'https://github.com/pocketbase/pocketbase', description: 'Open-source Go backend in 1 file.', stars: '41.2k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Firebase', slug: 'firebase', startingPrice: 'Free (Pay-as-you-go)', freeTier: true, featureParity: '95%', keyAdvantage: 'Native Google Mobile SDK & Firestore document database.' },
      { name: 'Neon', slug: 'neon', startingPrice: 'Free / $19', freeTier: true, featureParity: '90%', keyAdvantage: 'Serverless Postgres database branching.' },
    ],
  },
  {
    name: 'Vercel',
    slug: 'vercel',
    categoryName: 'Hosting & Infrastructure',
    categorySlug: 'hosting',
    shortDescription: 'Frontend cloud platform for static and serverless web deployment.',
    summary: 'Vercel provides automated Git deployments, edge network caching, and Next.js serverless execution.',
    websiteUrl: 'https://vercel.com',
    aliases: ['Vercel Cloud', 'ZEIT'],
    assessment: {
      buildComplexity: 3,
      integrationDependency: 4,
      dataMoat: 2,
      networkEffects: 3,
      complianceRequirement: 3,
      infrastructureComplexity: 3,
      realtimeCollaboration: 2,
      maintenanceBurden: 2,
      businessCriticality: 4,
      migrationComplexity: 2,
      apiAvailability: 4,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 5,
      dataPortability: 4,
      mobileDependency: 1,
      permissionComplexity: 3,
      reliabilityRequirement: 5,
      vendorLockIn: 2,
    },
    pricing: [
      { name: 'Hobby', billingInterval: 'monthly', basePrice: 0, pricePerSeat: 0, freeTier: true },
      { name: 'Pro', billingInterval: 'monthly', basePrice: 20, pricePerSeat: 20, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Vercel Official Site', url: 'https://vercel.com' },
    ],
    openSourceAlternatives: [
      { name: 'Coolify', githubUrl: 'https://github.com/coollabsio/coolify', description: 'Self-hostable Heroku & Vercel alternative.', stars: '36.8k★' },
      { name: 'Dokku', githubUrl: 'https://github.com/dokku/dokku', description: 'Docker powered mini-Heroku in 100 lines.', stars: '26.1k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Netlify', slug: 'netlify', startingPrice: 'Free / $19', freeTier: true, featureParity: '96%', keyAdvantage: 'Robust static form processing & identity management.' },
      { name: 'Cloudflare Pages', slug: 'cloudflare-pages', startingPrice: 'Free', freeTier: true, featureParity: '92%', keyAdvantage: 'Zero bandwidth charges on global edge network.' },
    ],
  },
  {
    name: 'Plausible',
    slug: 'plausible',
    categoryName: 'Product Analytics',
    categorySlug: 'analytics',
    shortDescription: 'Lightweight and privacy-friendly open-source web analytics.',
    summary: 'Plausible offers cookie-free website analytics with a sub-1KB tracking script.',
    websiteUrl: 'https://plausible.io',
    aliases: ['Plausible Analytics'],
    assessment: {
      buildComplexity: 2,
      integrationDependency: 2,
      dataMoat: 2,
      networkEffects: 1,
      complianceRequirement: 4,
      infrastructureComplexity: 2,
      realtimeCollaboration: 1,
      maintenanceBurden: 2,
      businessCriticality: 3,
      migrationComplexity: 1,
      apiAvailability: 4,
      workflowAutomatable: 3,
      openSourceMaturity: 5,
      alternativeMarketStrength: 4,
      dataPortability: 5,
      mobileDependency: 1,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 1,
    },
    pricing: [
      { name: 'Growth', billingInterval: 'monthly', basePrice: 9, pricePerSeat: 0, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Plausible Official Site', url: 'https://plausible.io' },
    ],
    openSourceAlternatives: [
      { name: 'Plausible CE', githubUrl: 'https://github.com/plausible/analytics', description: 'Open-source privacy-focused web analytics.', stars: '19.4k★' },
      { name: 'Umami', githubUrl: 'https://github.com/umami-software/umami', description: 'Modern open-source website analytics.', stars: '21.5k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Fathom Analytics', slug: 'fathom', startingPrice: '$15/mo', freeTier: false, featureParity: '95%', keyAdvantage: 'Bypasses ad blockers via custom domain routing.' },
      { name: 'Simple Analytics', slug: 'simple-analytics', startingPrice: '$9/mo', freeTier: false, featureParity: '90%', keyAdvantage: '100% GDPR compliant with automated PDF export.' },
    ],
  },
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    categoryName: 'AI Voice & Audio',
    categorySlug: 'audio',
    shortDescription: 'AI voice generator and voice cloning platform for realistic speech synthesis.',
    summary: 'ElevenLabs produces natural human-like voiceovers and audio translations across multiple languages.',
    websiteUrl: 'https://elevenlabs.io',
    aliases: ['Eleven Labs', 'ElevenLabs AI'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 3,
      dataMoat: 4,
      networkEffects: 1,
      complianceRequirement: 3,
      infrastructureComplexity: 4,
      realtimeCollaboration: 1,
      maintenanceBurden: 3,
      businessCriticality: 3,
      migrationComplexity: 2,
      apiAvailability: 5,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 4,
      dataPortability: 4,
      mobileDependency: 1,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 2,
    },
    pricing: [
      { name: 'Starter', billingInterval: 'monthly', basePrice: 5, pricePerSeat: 0, freeTier: true },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'ElevenLabs Official Site', url: 'https://elevenlabs.io' },
    ],
    openSourceAlternatives: [
      { name: 'Bark (Suno)', githubUrl: 'https://github.com/suno-ai/bark', description: 'Transformer-based audio generation model.', stars: '34.2k★' },
      { name: 'XTTS v2 (Coqui)', githubUrl: 'https://github.com/coqui-ai/TTS', description: 'Deep learning toolkit for Text-to-Speech.', stars: '32.1k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Play.ht', slug: 'play-ht', startingPrice: '$29/mo', freeTier: true, featureParity: '92%', keyAdvantage: 'Instant podcast feed hosting & publishing.' },
      { name: 'Speechify', slug: 'speechify', startingPrice: '$11.58/mo', freeTier: true, featureParity: '88%', keyAdvantage: 'High-speed document reading apps for iOS/Android.' },
    ],
  },
  {
    name: 'Linear',
    slug: 'linear',
    categoryName: 'Project Management',
    categorySlug: 'project-management',
    shortDescription: 'Issue tracking and project management tool built for high-velocity software engineering teams.',
    summary: 'Linear provides keyboard-driven task tracking, Git integration, and automated cycle planning for developers.',
    websiteUrl: 'https://linear.app',
    aliases: ['Linear App', 'Linear Issue Tracker'],
    assessment: {
      buildComplexity: 4,
      integrationDependency: 4,
      dataMoat: 3,
      networkEffects: 2,
      complianceRequirement: 3,
      infrastructureComplexity: 3,
      realtimeCollaboration: 4,
      maintenanceBurden: 3,
      businessCriticality: 4,
      migrationComplexity: 3,
      apiAvailability: 5,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 5,
      dataPortability: 4,
      mobileDependency: 3,
      permissionComplexity: 3,
      reliabilityRequirement: 5,
      vendorLockIn: 3,
    },
    pricing: [
      { name: 'Free', billingInterval: 'monthly', basePrice: 0, pricePerSeat: 0, freeTier: true },
      { name: 'Standard', billingInterval: 'monthly', basePrice: 10, pricePerSeat: 8, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Linear Official Site', url: 'https://linear.app' },
    ],
    openSourceAlternatives: [
      { name: 'Plane', githubUrl: 'https://github.com/makeplane/plane', description: 'Open-source project management platform.', stars: '28.9k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Jira', slug: 'jira', startingPrice: 'Free / $8.15', freeTier: true, featureParity: '98%', keyAdvantage: 'Enterprise compliance & Atlassian ecosystem.' },
      { name: 'ClickUp', slug: 'clickup', startingPrice: '$10/mo', freeTier: true, featureParity: '94%', keyAdvantage: 'Includes docs, goals, and multi-team views.' },
    ],
  },
  {
    name: 'Typefully',
    slug: 'typefully',
    categoryName: 'Social Media Management',
    categorySlug: 'social-media',
    shortDescription: 'Distraction-free editor and publisher for X (Twitter) threads, LinkedIn posts, and social analytics.',
    summary: 'Typefully helps creators and growth teams write, schedule, and analyze high-performing social content with AI auto-complete and multi-account publishing.',
    websiteUrl: 'https://typefully.com',
    aliases: ['Typefully App', 'Type fully'],
    assessment: {
      buildComplexity: 2,
      integrationDependency: 3,
      dataMoat: 2,
      networkEffects: 2,
      complianceRequirement: 1,
      infrastructureComplexity: 2,
      realtimeCollaboration: 2,
      maintenanceBurden: 2,
      businessCriticality: 3,
      migrationComplexity: 1,
      apiAvailability: 4,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 4,
      dataPortability: 4,
      mobileDependency: 2,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 1,
    },
    pricing: [
      { name: 'Free', billingInterval: 'monthly', basePrice: 0, pricePerSeat: 0, freeTier: true },
      { name: 'Creator', billingInterval: 'monthly', basePrice: 12.5, pricePerSeat: 0, freeTier: false },
      { name: 'Team', billingInterval: 'monthly', basePrice: 29, pricePerSeat: 10, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Typefully Official Site', url: 'https://typefully.com' },
    ],
    openSourceAlternatives: [
      { name: 'Postiz', githubUrl: 'https://github.com/gitroomhq/postiz-app', description: 'Open-source AI social media scheduler.', stars: '14.2k★' },
      { name: 'Mixpost', githubUrl: 'https://github.com/inovector/mixpost', description: 'Self-hosted social media management software.', stars: '3.6k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Buffer', slug: 'buffer', startingPrice: '$6/mo', freeTier: true, featureParity: '92%', keyAdvantage: 'Multi-platform support including Instagram & TikTok.' },
      { name: 'FeedHive', slug: 'feedhive', startingPrice: '$19/mo', freeTier: false, featureParity: '94%', keyAdvantage: 'Visual drag-and-drop social content calendar.' },
    ],
  },
  {
    name: 'Plausible',
    slug: 'plausible',
    categoryName: 'Analytics & Reporting',
    categorySlug: 'analytics',
    shortDescription: 'Lightweight and open-source Google Analytics alternative with 100% privacy compliance.',
    summary: 'Plausible Analytics provides cookie-free web metrics under 1KB with zero cross-site tracking, fully compliant with GDPR and CCPA regulations.',
    websiteUrl: 'https://plausible.io',
    aliases: ['Plausible Analytics', 'Plausible IO'],
    assessment: {
      buildComplexity: 2,
      integrationDependency: 2,
      dataMoat: 2,
      networkEffects: 1,
      complianceRequirement: 4,
      infrastructureComplexity: 2,
      realtimeCollaboration: 1,
      maintenanceBurden: 2,
      businessCriticality: 4,
      migrationComplexity: 1,
      apiAvailability: 4,
      workflowAutomatable: 4,
      openSourceMaturity: 5,
      alternativeMarketStrength: 5,
      dataPortability: 5,
      mobileDependency: 1,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 1,
    },
    pricing: [
      { name: 'Growth', billingInterval: 'monthly', basePrice: 9, pricePerSeat: 0, freeTier: false },
      { name: 'Business', billingInterval: 'monthly', basePrice: 19, pricePerSeat: 0, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Plausible Official Site', url: 'https://plausible.io' },
      { type: 'GITHUB', title: 'Plausible GitHub Repository', url: 'https://github.com/plausible/analytics' },
    ],
    openSourceAlternatives: [
      { name: 'Plausible Self-Hosted', githubUrl: 'https://github.com/plausible/analytics', description: 'Open-source web analytics platform.', stars: '18.5k★' },
      { name: 'Umami', githubUrl: 'https://github.com/umami-software/umami', description: 'Fast, privacy-focused open-source analytics.', stars: '21.4k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Fathom Analytics', slug: 'fathom', startingPrice: '$15/mo', freeTier: false, featureParity: '96%', keyAdvantage: 'Uptime monitoring included & GDPR compliance.' },
      { name: 'Simple Analytics', slug: 'simple-analytics', startingPrice: '$9/mo', freeTier: false, featureParity: '90%', keyAdvantage: 'Zero cookie banners & instant CSV/JSON exports.' },
    ],
  },
  {
    name: 'Fathom Analytics',
    slug: 'fathom',
    categoryName: 'Analytics & Reporting',
    categorySlug: 'analytics',
    shortDescription: 'Simple, privacy-first website analytics alternative to Google Analytics.',
    summary: 'Fathom Analytics tracks traffic metrics without compromising visitor privacy or loading slow scripts.',
    websiteUrl: 'https://usefathom.com',
    aliases: ['Fathom', 'UseFathom'],
    assessment: {
      buildComplexity: 2,
      integrationDependency: 2,
      dataMoat: 2,
      networkEffects: 1,
      complianceRequirement: 4,
      infrastructureComplexity: 2,
      realtimeCollaboration: 1,
      maintenanceBurden: 2,
      businessCriticality: 4,
      migrationComplexity: 1,
      apiAvailability: 4,
      workflowAutomatable: 4,
      openSourceMaturity: 4,
      alternativeMarketStrength: 5,
      dataPortability: 5,
      mobileDependency: 1,
      permissionComplexity: 2,
      reliabilityRequirement: 4,
      vendorLockIn: 1,
    },
    pricing: [
      { name: 'Starter', billingInterval: 'monthly', basePrice: 15, pricePerSeat: 0, freeTier: false },
    ],
    sources: [
      { type: 'OFFICIAL_WEBSITE', title: 'Fathom Official Site', url: 'https://usefathom.com' },
    ],
    openSourceAlternatives: [
      { name: 'Umami', githubUrl: 'https://github.com/umami-software/umami', description: 'Open-source web analytics.', stars: '21.4k★' },
      { name: 'Ackee', githubUrl: 'https://github.com/electerious/ackee', description: 'Node.js privacy-focused analytics.', stars: '4.2k★' },
    ],
    verifiedCommercialAlternatives: [
      { name: 'Plausible', slug: 'plausible', startingPrice: '$9/mo', freeTier: false, featureParity: '96%', keyAdvantage: 'Open-source code transparency & self-hostable core.' },
      { name: 'PostHog', slug: 'posthog', startingPrice: 'Free / $0.0001', freeTier: true, featureParity: '85%', keyAdvantage: 'Includes session recording, feature flags, & product analytics.' },
    ],
  },
];
